displayName: TLS client certificate serial number forward
type: middleware

import: github.com/v-electrolux/tlsclientcertforward

summary: |
  Built-in traefik middleware PassTLSClientCert
  let you pass many certificate parameters such as common name or serial number.
  But all parameter passed in one header value,
  so you can not get just pure certificate serial number in header.
  This middleware solves this problem for you. It extracts just pure SN value and put in a header

testData:
  snHeaderName: Forwarded-Tls-Client-Cert-Dec-Sn
